package view;

import dao.DAOMovimentacao;
import dao.DAOPessoa;
import dao.DAOProduto;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ModeloMovimentacao;
import modelo.ModeloPessoa;
import modelo.ModeloProduto;

public class viewEmprestimo extends javax.swing.JInternalFrame {

    ModeloProduto produto = new ModeloProduto();
    ModeloPessoa pessoa = new ModeloPessoa();
    DAOMovimentacao dao = new DAOMovimentacao();
    DAOProduto daop = new DAOProduto();
    DAOPessoa daopess = new DAOPessoa();
    ModeloMovimentacao movimentacao = new ModeloMovimentacao();

    public boolean validaCampos() {
        if (!(jcbxPessoa.getSelectedIndex() >= 1)) {
            JOptionPane.showMessageDialog(null, "Informe a pessoa!");
            jcbxPessoa.requestFocus();
            return false;
        }
        if (!(jcbxProduto.getSelectedIndex() >= 1)) {
            JOptionPane.showMessageDialog(null, "Informe o produto!");
            jcbxProduto.requestFocus();
            return false;
        }
        if (!(jtfQtd.getText().length() > 0)) {
            JOptionPane.showMessageDialog(null, "Informe a quantidade do empréstimo!");
            jtfQtd.requestFocus();
            return false;
        }
        return true;
    }

    public void readJTable() {

        DefaultTableModel modelo = (DefaultTableModel) jtbEmprestimo.getModel();
        modelo.setNumRows(0);

        for (ModeloMovimentacao e : dao.readEprestimo()) {

            modelo.addRow(new Object[]{
                e.getIdMovimentacao(),
                e.getDataMovimentacaoSTR(),
                e.getQtdMovimentacao(),
                e.getTempProduto(),
                e.getTemPessoa(),
                e.getSituacao(),
                e.getDataDevolucaoSTR()

            });
        }

    }

    public viewEmprestimo() {
        initComponents();
        readJTable();

        for (ModeloPessoa o : daopess.readPessoa()) {
            jcbxPessoa.addItem(o);
        }

        for (ModeloProduto p : daop.readProduto()) {
            jcbxProduto.addItem(p);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanelCadEmprest4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtbEmprestimo = new javax.swing.JTable();
        jbtnDevolver = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanelCadEmprest5 = new javax.swing.JPanel();
        jlblNomeServ4 = new javax.swing.JLabel();
        jlblDescEmprest4 = new javax.swing.JLabel();
        jlblProdEmprest4 = new javax.swing.JLabel();
        jcbxProduto = new javax.swing.JComboBox();
        jcbxPessoa = new javax.swing.JComboBox();
        jlblQtd3 = new javax.swing.JLabel();
        jtfQtd = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtaDescricao = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jbtnSalvarProd4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Empréstimos");
        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(840, 523));
        setPreferredSize(new java.awt.Dimension(840, 523));

        jPanelCadEmprest4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gerenciamento de empréstimos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(204, 0, 0))); // NOI18N

        jtbEmprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Data", "Quantidade", "Produto", "Pessoa", "Situação", "Data devolução"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbEmprestimo.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jtbEmprestimo);
        if (jtbEmprestimo.getColumnModel().getColumnCount() > 0) {
            jtbEmprestimo.getColumnModel().getColumn(0).setPreferredWidth(5);
            jtbEmprestimo.getColumnModel().getColumn(1).setResizable(false);
            jtbEmprestimo.getColumnModel().getColumn(1).setPreferredWidth(100);
            jtbEmprestimo.getColumnModel().getColumn(2).setPreferredWidth(40);
            jtbEmprestimo.getColumnModel().getColumn(3).setResizable(false);
            jtbEmprestimo.getColumnModel().getColumn(3).setPreferredWidth(100);
            jtbEmprestimo.getColumnModel().getColumn(4).setResizable(false);
            jtbEmprestimo.getColumnModel().getColumn(4).setPreferredWidth(100);
            jtbEmprestimo.getColumnModel().getColumn(5).setResizable(false);
            jtbEmprestimo.getColumnModel().getColumn(5).setPreferredWidth(35);
            jtbEmprestimo.getColumnModel().getColumn(6).setResizable(false);
        }

        jbtnDevolver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnDevolver.setText("Devolver");
        jbtnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDevolverActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgens/update.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadEmprest4Layout = new javax.swing.GroupLayout(jPanelCadEmprest4);
        jPanelCadEmprest4.setLayout(jPanelCadEmprest4Layout);
        jPanelCadEmprest4Layout.setHorizontalGroup(
            jPanelCadEmprest4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadEmprest4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadEmprest4Layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jbtnDevolver, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addGap(299, 299, 299))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadEmprest4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelCadEmprest4Layout.setVerticalGroup(
            jPanelCadEmprest4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadEmprest4Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnDevolver)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadEmprest4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelCadEmprest4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listagem", jPanel1);

        jPanelCadEmprest5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Novo empréstimo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(204, 0, 0))); // NOI18N

        jlblNomeServ4.setText("Nome:");

        jlblDescEmprest4.setText("Descrição:");

        jlblProdEmprest4.setText("Produto:");

        jcbxProduto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um produto..." }));

        jcbxPessoa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma pessoa..." }));

        jlblQtd3.setText("Quantidade:");

        jtaDescricao.setColumns(20);
        jtaDescricao.setLineWrap(true);
        jtaDescricao.setRows(3);
        jScrollPane5.setViewportView(jtaDescricao);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("* Campo obrigatório");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("*");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("*");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 0));
        jLabel26.setText("*");

        jbtnSalvarProd4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnSalvarProd4.setText("Salvar");
        jbtnSalvarProd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSalvarProd4ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setText("Limpar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCadEmprest5Layout = new javax.swing.GroupLayout(jPanelCadEmprest5);
        jPanelCadEmprest5.setLayout(jPanelCadEmprest5Layout);
        jPanelCadEmprest5Layout.setHorizontalGroup(
            jPanelCadEmprest5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadEmprest5Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jbtnSalvarProd4, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(136, 136, 136)
                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addGap(141, 141, 141))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCadEmprest5Layout.createSequentialGroup()
                .addGroup(jPanelCadEmprest5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadEmprest5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelCadEmprest5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(jPanelCadEmprest5Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jScrollPane5))))
                    .addGroup(jPanelCadEmprest5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jlblNomeServ4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbxPessoa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCadEmprest5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanelCadEmprest5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadEmprest5Layout.createSequentialGroup()
                                .addComponent(jlblDescEmprest4)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanelCadEmprest5Layout.createSequentialGroup()
                                .addComponent(jlblProdEmprest4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlblQtd3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(jtfQtd)))))
                .addGap(79, 79, 79))
        );
        jPanelCadEmprest5Layout.setVerticalGroup(
            jPanelCadEmprest5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadEmprest5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelCadEmprest5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbxPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jlblNomeServ4))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadEmprest5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblProdEmprest4)
                    .addComponent(jcbxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jtfQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jlblQtd3))
                .addGap(18, 18, 18)
                .addGroup(jPanelCadEmprest5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCadEmprest5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jlblDescEmprest4)))
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(62, 62, 62)
                .addGroup(jPanelCadEmprest5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jbtnSalvarProd4))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCadEmprest5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanelCadEmprest5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Adicionar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSalvarProd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSalvarProd4ActionPerformed
        //ação do botão salvar empréstimo

        if (validaCampos()) {

            pessoa = (ModeloPessoa) jcbxPessoa.getSelectedItem();

            movimentacao.setFKpessoa(pessoa.getIdPessoa());

            produto = (ModeloProduto) jcbxProduto.getSelectedItem();
            movimentacao.setFKproduto(produto.getIdProduto());

            movimentacao.setTipoMovimentacao("Empréstimo");
            movimentacao.setSituacao("Pendente");

            movimentacao.setQtdMovimentacao(Integer.parseInt(jtfQtd.getText()));

            //  java.util.Date RecebeData = jdcData.getDate();
            // movimentacao.setDataMovimentacao(RecebeData);
            movimentacao.setDataMovimentacaoSTR(new SimpleDateFormat("yyyy/MM/dd HH:mm").format(new Date(System.currentTimeMillis())));

            if (jtaDescricao.getText() == null) {
                movimentacao.setDescricaoMovimentacao("Nenhuma");
            } else {
                movimentacao.setDescricaoMovimentacao(jtaDescricao.getText());
            }

            //  daopess.obterPessoa(pessoa);
            daop.obterProduto(produto);

            if (produto.getQtdEstoque() > 0 && movimentacao.getQtdMovimentacao() <= produto.getQtdEstoque()) {
                dao.insereSaidaEmprestimo(movimentacao);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Quantia insuficiente no estoque!");
            }

            jcbxPessoa.setSelectedIndex(0);
            jcbxProduto.setSelectedIndex(0);
            jtfQtd.setText("");
            jtaDescricao.setText("");

            readJTable();
            jTabbedPane1.setSelectedIndex(0);

        }


    }//GEN-LAST:event_jbtnSalvarProd4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // ação do botão limpar

        jcbxPessoa.setSelectedIndex(0);
        jcbxProduto.setSelectedIndex(0);
        jtfQtd.setText("");
        jtaDescricao.setText("");


    }//GEN-LAST:event_jButton9ActionPerformed

    private void jbtnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDevolverActionPerformed
        // ação do botão devolver

        if (jtbEmprestimo.getSelectedRow() != -1) {
            if ((jtbEmprestimo.getValueAt(jtbEmprestimo.getSelectedRow(), 6)) != null) {
                JOptionPane.showMessageDialog(null, "Empréstimo já foi devolvido!");
            } else {

                movimentacao.setIdMovimentacao((int) jtbEmprestimo.getValueAt(jtbEmprestimo.getSelectedRow(), 0));
                movimentacao.setTempProduto((String) jtbEmprestimo.getValueAt(jtbEmprestimo.getSelectedRow(), 3));
                movimentacao.setQtdMovimentacao((int) jtbEmprestimo.getValueAt(jtbEmprestimo.getSelectedRow(), 2));
                movimentacao.setDataDevolucaoSTR(new SimpleDateFormat("yyyy/MM/dd HH:mm").format(new Date(System.currentTimeMillis())));

                dao.obterIdProduto(movimentacao);

                dao.DevolveEmpréstimo(movimentacao);
                readJTable();

            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um empréstimo!");
        }


    }//GEN-LAST:event_jbtnDevolverActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // ação do botão atualizar

        readJTable();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCadEmprest4;
    private javax.swing.JPanel jPanelCadEmprest5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnDevolver;
    private javax.swing.JButton jbtnSalvarProd4;
    private javax.swing.JComboBox jcbxPessoa;
    private javax.swing.JComboBox jcbxProduto;
    private javax.swing.JLabel jlblDescEmprest4;
    private javax.swing.JLabel jlblNomeServ4;
    private javax.swing.JLabel jlblProdEmprest4;
    private javax.swing.JLabel jlblQtd3;
    private javax.swing.JTextArea jtaDescricao;
    private javax.swing.JTable jtbEmprestimo;
    private javax.swing.JTextField jtfQtd;
    // End of variables declaration//GEN-END:variables
}
